### ISSUE TITLE
Redistribution of Mecab requires some conditions and they are not met

### ISSUE THREAD

**Issue by HiromuHota** [polm/fugashi#20]
According to https://github.com/taku910/mecab/blob/master/mecab/COPYING, 
> MeCab is copyrighted free software by Taku Kudo <taku@chasen.org> and
Nippon Telegraph and Telephone Corporation, and is released under
any of the GPL (see the file GPL), the LGPL (see the file LGPL), or the
BSD License (see the file BSD).

In the case of BSD, https://github.com/taku910/mecab/blob/master/mecab/BSD says
>  * Redistributions in binary form must reproduce the above
   copyright notice, this list of conditions and the
   following disclaimer in the documentation and/or other
   materials provided with the distribution.

I think this applies to fugashi, which redistributes libmecab (a binary file).

Disclaimer: I'm not a lawyer and this is not a legal advice.

**Comment by polm** [comment]
Thanks, I hadn't thought of that!
