### ISSUE TITLE
Issue using fugashi with transformers[ja]==3.1.0

### ISSUE THREAD

**Issue by Mukei** [polm/fugashi#24]
Hi,
I was importing transformer[ja] on Colab without any issue, but as I moved my code locally it start failing.

I am on a Mac (Catalina) and use Pycharm.

In my _requirements.txt_ file I have `transformers[ja]==3.1.0` and when I run some code I get the below error message
```
Failed initializing MeCab. Please see the README for possible solutions:
...
self.mecab = fugashi.GenericTagger(mecab_option)
  File "fugashi/fugashi.pyx", line 220, in fugashi.fugashi.GenericTagger.__init__
RuntimeError: Failed initializing MeCab
```
Any suggestions?

I tried adding the below to the requirements.txt but without success.
```
mecab-python3==1.0.1
unidic-lite==1.0.7
ipadic==1.0.0
unidic==1.0.2
```

**Comment by polm** [comment]
Hm, that's strange.

Could you please copy the part of the error output that says `ERROR DETAILS`?

What happens when you run `fugashi` at the command line?

What happens if you uninstall unidic, but leave in unidic-lite, and run it at the command line?

Also, you do not need mecab-python3, it is not doing anything.

**Comment by Mukei** [comment]
Hi @polm, Thank you for your reply!

The error happens in `tokenizer = BertJapaneseTokenizer.from_pretrained(pretrained)`.
Let me share with you a sample code and the associated error below.

### main.py
```python
from transformers import BertJapaneseTokenizer


class Main(object):
    def __init__(self):
        self.pretrained = 'cl-tohoku/bert-base-japanese-whole-word-masking'
        self.tokenizer = BertJapaneseTokenizer.from_pretrained(self.pretrained)


if __name__ == '__main__':
    main = Main()
```

### requirements.txt
```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile requirements.txt
#
certifi==2020.6.20        # via requests
chardet==3.0.4            # via requests
click==7.1.2              # via sacremoses
filelock==3.0.12          # via transformers
fugashi==1.0.4            # via transformers
idna==2.10                # via requests
ipadic==1.0.0             # via transformers
joblib==0.16.0            # via sacremoses
numpy==1.19.2             # via transformers
packaging==20.4           # via transformers
plac==1.2.0               # via unidic
pyparsing==2.4.7          # via packaging
regex==2020.7.14          # via sacremoses, transformers
requests==2.24.0          # via transformers, unidic
sacremoses==0.0.43        # via transformers
sentencepiece==0.1.91     # via transformers
six==1.15.0               # via packaging, sacremoses
tokenizers==0.8.1.rc2     # via transformers
tqdm==4.49.0              # via sacremoses, transformers, unidic
transformers[ja]==3.1.0   # via -r requirements.txt
unidic-lite==1.0.7        # via transformers
unidic==1.0.2             # via transformers
urllib3==1.25.10          # via requests
wasabi==0.8.0             # via unidic
```

### Error Details
```
------------------- ERROR DETAILS ------------------------
arguments: [b'fugashi', b'-C', b'-d', b'/Users/userName', b'pythonProject/Transformers310FugashiTest/venv/lib/python3.7/site-packages/ipadic/dicdir', b'-r', b'/Users/userName', b'pythonProject/Transformers310FugashiTest/venv/lib/python3.7/site-packages/ipadic/dicdir/mecabrc']
error message: param.cpp(69) [ifs] no such file or directory: /Users/userNameUsers/userName/main.py", line 14, in <module>
    main = Main()
  File "/Users/userName/main.py", line 10, in __init__
    self.tokenizer = BertJapaneseTokenizer.from_pretrained(self.pretrained)
  File "/Users/userName/venv/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1425, in from_pretrained
----------------------------------------------------------
    return cls._from_pretrained(*inputs, **kwargs)
  File "/Users/userName/venv/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1572, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/Users/userName/venv/lib/python3.7/site-packages/transformers/tokenization_bert_japanese.py", line 139, in __init__
    do_lower_case=do_lower_case, never_split=never_split, **(mecab_kwargs or {})
  File "/Users/userName/venv/lib/python3.7/site-packages/transformers/tokenization_bert_japanese.py", line 254, in __init__
    self.mecab = fugashi.GenericTagger(mecab_option)
  File "fugashi/fugashi.pyx", line 220, in fugashi.fugashi.GenericTagger.__init__
RuntimeError: Failed initializing MeCab

Process finished with exit code 1
```

**Comment by polm** [comment]
OK, based on the `arguments` in `ERROR_DETAILS` it looks like the path to your virtualenv has something wrong with it.

    b'-d', b'/Users/userName', b'pythonProject/Transformers310FugashiTest/venv/lib/python3.7/site-packages/ipadic/dicdir'

It should probably look like this:

    b'-d', b'/Users/userName/pythonProject/Transformers310FugashiTest/venv/lib/python3.7/site-packages/ipadic/dicdir'

Is there a space in the path to your `pythonProject` directory or something? fugashi should work even with a space in the path, but it could potentially cause issues. 

Also, **please try running fugashi from the command line and tell me if that works.**

**Comment by Mukei** [comment]
@polm, thanks for the hints 👍 
Indeed the path included spaces.
![image](https://user-images.githubusercontent.com/266090/93196584-97efaf00-f785-11ea-9c32-050359c0226a.png)

I moved project to a path with no spaces, and I could run the above _main.py_ without any error. Hence, directories with spaces do not seem to be supported well.
![image](https://user-images.githubusercontent.com/266090/93196607-9de59000-f785-11ea-9298-16f07d9e53ca.png)

However, while in the new path, using a python console with the below code, I got an error:
```python
from fugashi import Tagger
tagger = Tagger('-Owakati')
```

### Error Message
```
------------------- ERROR DETAILS ------------------------
arguments: [b'fugashi', b'-C', b'-r', b'/Users/thomastelandro/Documents/Transformers310FugashiTest/venv/lib/python3.7/site-packages/unidic/dicdir/mecabrc', b'-d', b'/Users/thomastelandro/Documents/Transformers310FugashiTest/venv/lib/python3.7/site-packages/unidic/dicdir', b'-Owakati']
error message: param.cpp(69) [ifs] no such file or directory: /Users/thomastelandro/Documents/Transformers310FugashiTest/venv/lib/python3.7/site-packages/unidic/dicdir/mecabrc
----------------------------------------------------------
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "fugashi/fugashi.pyx", line 313, in fugashi.fugashi.Tagger.__init__
  File "fugashi/fugashi.pyx", line 220, in fugashi.fugashi.GenericTagger.__init__
RuntimeError: Failed initializing MeCab
```

**Comment by polm** [comment]
OK, I'll look into the spaces issues. 

For UniDic you have to run the download command, please see [the README](https://github.com/polm/unidic-py).

    python -m unidic download

**Comment by polm** [comment]
Turns out the issue with spaces in the path is Transformers-specific, I've opened a PR there.

If downloading UniDic fixes your issue please confirm. If you aren't actually planning to use UniDic, please uninstall the pip package and then it should work when fugashi uses unidic-lite by default.

**Comment by Mukei** [comment]
running the download command solved all my issue.
Thank you so much for your time! That really helped 🙇‍♂️
