### ISSUE TITLE
Pronounce without 「ー」 (kana only)

### ISSUE THREAD

**Issue by pedrominicz** [polm/fugashi#26]
How do I get the pronounce of a word without 「ー」? For example, I would like the following to print 「ケッコウ」.
```
from fugashi import Tagger
tagger = Tagger()
print([word.feature.pron for word in tagger('結構')])
```
On a related note, where can I find documentation for the library (for example, about the fields of `word.feature`)?

**Comment by polm** [comment]
You want the `kana` attribute. 

```
import fugashi
tagger = fugashi.Tagger()
words = tagger("講師と子牛")
for word in words:
    print(word.surface, word.feature.pron, word.feature.kana)
```

Results:

```
講師 コーシ コウシ
と ト ト
子牛 コウシ コウシ
```

Note that the `pron` field distinguishes punctuation more than the `kana` field.

The fields are documented in the [UniDic FAQ](https://unidic.ninjal.ac.jp/faq#col_name), though admittedly the explanation is limited. I'll see about adding an English version.

Also note the fields depend on the dictionary you're using, though for UniDic dictionaries most of the fields are shared between versions.

**Comment by pedrominicz** [comment]
Thanks, this works perfectly! Thank you very much for maintaining this and `mecab-python3`!
