### ISSUE TITLE
Wheel for Windows?

### ISSUE THREAD

**Issue by chezou** [polm/fugashi#3]
It's hard to build fugashi in Windows because
- long_description in setup.py doesn't have encoding so that parsing setup.py fails
- lacking include_dirs for Extension prevents finding mecab.h
- Unable to find mecab.dll without having library_dirs for Extension
etc etc...

When I built mecab python binding wheel for Windows I included everything (dll, header) in a wheel, not sure it is a good way though. https://github.com/chezou/mecab/blob/master/mecab/python/setup.py#L23-L34

It'd be appreciated if you could provide Windows wheel, we can reduce compilation issues.

**Comment by polm** [comment]
Thanks for the notice! I've been meaning to add wheels and having Windows support is important. Unfortunately I do not have a Windows dev environment or know how to use one so I can't test this. 

If I copy the settings from your linked code and put it in a branch could you test it?

**Comment by chezou** [comment]
Sure, definitely I can evaluate the setting. Also, we now have GitHub Actions which is good platform to build wheel for Windows as well.

**Comment by polm** [comment]
OK, I pushed a `windows` branch incorporating the settings you linked to, let me know if that works. I'll look into setting up Github Actions too. 

As a note, the code you linked seems like it doesn't run? Starting on line 31 the references to `mecab_config` use a hyphen instead of an underscore.

**Comment by chezou** [comment]
ah, that should be fixed. honestly I used this branch only for building the Windows wheel.
here is the entire diff with upstream.
https://github.com/taku910/mecab/compare/master...chezou:master

**Comment by chezou** [comment]
I didn't run yet, but seems Windows branch doesn't work since Windows mecab doesn't provide mecab-config since it's just a shell script.

**Comment by polm** [comment]
OK, I updated the branch so mecab-config won't be called at all on Windows.

**Comment by chezou** [comment]
Finally, I got installed with my wheel built locally. Congratulations!

# Prerequisites
- Download prebuild 64bit mecab from https://github.com/chezou/mecab/releases and extract on C:\mecab
- Install Cython before `python setup.py bdist_wheel`

For the detailed reason for installing my pre-build dll for MeCab, see this article:
https://chezo.uno/post/2018-12-01_windows-64bit-mecab-kytea-2018-b283b6c7b33c/

# Example code

After creating the wheel, I created another venv and installed as follows:

```
λ  pip install ..\fugashi\dist\fugashi-0.1.5-cp36-cp36m-win_amd64.whl
Processing c:\users\chezo\source\fugashi\dist\fugashi-0.1.5-cp36-cp36m-win_amd64.whl
Collecting Cython (from fugashi==0.1.5)
  Using cached https://files.pythonhosted.org/packages/ca/5d/7344d00b55f060243cf4f04c2fcee8c245a0af2b0bc236fc6dbb5021dcd6/Cython-0.29.14-cp36-cp36m-win_amd64.whl
Installing collected packages: Cython, fugashi
Successfully installed Cython-0.29.14 fugashi-0.1.5
You are using pip version 19.0.2, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
C:\Users\chezo\source\fugashi-test
λ  python
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from fugashi import Tagger
>>> tagger = Tagger('-Owakati')
>>> tagger.parse("麩菓子（ふがし）は、麩を主材料とした日本の菓子。")
'麩 菓子 （ ふ が し ） は 、 麩 を 主 材料 と し た 日本 の 菓子 。'
```

This means, providing wheels for Windows enables Windows users to install without having C compiler!

## Caveats & concernings

Note that I couldn't import fugashi with editable install, i.e., `pip install -e .` .

```py
>>> from fugashi import Tagger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: 指定されたモジュールが見つかりません。
```

Also, I'm concerning the current setup.py assumes MeCab installed under `C:\mecab`, so it might be better to have an install parameter for setting MeCab directory.

**Comment by polm** [comment]
Thanks again - I managed to run the action successfully and upload the wheels. I'll add some notes to the README on Windows and we can think about whether there's a better way to specify the path.

**Comment by chezou** [comment]
There is a tricky way to add an option for setup.py. https://stackoverflow.com/a/33181352/3762316
It seems good for setting an additional path by using this technique.

**Comment by chezou** [comment]
Now I confirmed to install fugashi from PyPI with removing my local mecab as the following:

```
λ  pip install fugashi
Collecting fugashi
  Using cached https://files.pythonhosted.org/packages/3d/66/8cf850d08d76514030207afc1cce13fe6bf9dff962e8ebebc631a8f53613/fugashi-0.1.5-cp38-cp38-win_amd64.whl
Collecting Cython (from fugashi)
  Using cached https://files.pythonhosted.org/packages/41/2c/9d873fc8d1be29af12a1d41707461399327396da10e50e183754aa4136b9/Cython-0.29.14-cp38-cp38-win_amd64.whl
Installing collected packages: Cython, fugashi
Successfully installed Cython-0.29.14 fugashi-0.1.5
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
C:\Users\chezo\source\fugashi-test
λ  python
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from fugashi import Tagger
>>>
>>> tagger = Tagger('-Owakati')
>>> tagger.parse("麩菓子（ふがし）は、麩を主材料とした日本の菓子。")
'麩 菓子 （ ふ が し ） は 、 麩 を 主 材料 と し た 日本 の 菓子 。'
```

For reducing future issues on macOS. There can be several compilers i.e., Xcode based, brew based, and they sometimes cause compilation issue with Cython. It'd be better to have wheels for macOS as well.
