### ISSUE TITLE
posid is 1 for all tokens with Unidic

### ISSUE THREAD

**Issue by baker-ling** [polm/fugashi#34]
A Tagger instantiated with the default parameters (using Unidic) gives tokens a posid of 1, no matter what the part of speech actually is.

```
import fugashi

tagger = fugashi.Tagger()
test_string = "これから会議があります。"

print(tagger.dictionary_info[0]['filename'])
for token in tagger(test_string):
    print(token.surface + ": " + str(token.posid))
```
gives the output:
```
C:\Users\[omitted]\AppData\Local\Programs\Python\Python38\lib\site-packages\unidic\dicdir\sys.dic
これ: 1
から: 1
会議: 1
が: 1
あり: 1
ます: 1
。: 1
```
I tried instantiating a GenericTagger with Unidic, and it had the same problem.
```
import unidic
uni_generic_tagger = fugashi.GenericTagger(f'-d "{unidic.DICDIR}"')
```
However, a GenericTagger instantiated in the same way with IPAdic (from the ipadic PyPI package) does provide proper posids, so maybe this is an issue with Unidic.

**Comment by polm** [comment]
Huh, I'd never noticed that before. It looks like IPADic has a `pos-id.def` file, and UniDic is distributed without one, so that would explain why this happens. For reference the MeCab docs on the file are here:

https://taku910.github.io/mecab/posid.html

Is this causing you any problems or was it just something strange you noticed?

**Comment by baker-ling** [comment]
It is a problem, but not one I can't make a workaround for.

I was planning to use posids (along with cForms encoded as ordinal numbers) as features for some decision tree and random forest models in a project I am working on.

The workaround that comes to mind is to just encode PoS as ordinal numbers manually. Or from the link you posted, it looks like I could solve the root of the problem by writing the `pos-id.def ` file myself and recompiling Unidic. (Thanks for the idea.)
