### ISSUE TITLE
Look into using multi-py

### ISSUE THREAD

**Issue by polm** [polm/fugashi#47]
aarch64 support was just added, but the libmusl support may be interesting. 

https://github.com/multi-py

**Comment by lambdadog** [comment]
It looks like it's less for building wheels and testing (how you currently use docker images), and moreso a docker base image that developers can use to package their application.

Example: [The python-gunicorn container is built on by copying your Gunicorn app into ./app in the container.](https://github.com/multi-py/python-gunicorn#add-your-app)

It seems to be more designed for holistic "app frameworks" where the library is "all you need to make your app!" than anything, which makes it (IMO) not very suitable for packaging fugashi, which is more of a utility "I need X to make my app, so I'm going to install a library that does X" type of library.

**Comment by polm** [comment]
Thanks, that seems like a reasonable analysis.
