### ISSUE TITLE
Clean up setup.py

### ISSUE THREAD

**Issue by garfieldnate** [polm/fugashi#49]
Hi, 

this might be the same as #42 and #44, but the platform is different. I'm unable to load the .so file through fugashi when running from the base Docker image for Python 3.10. Minimal breaking example below:

Dockerfile:

    FROM python:3.10.1-bullseye
    RUN pip install -vvv fugashi
    RUN echo "import fugashi" | python

[Output](https://github.com/polm/fugashi/files/7730805/output.txt) of running `docker build 2>&1 .`.

If you know a quick workaround for this, I'd be happy to use that for now. I'd be happy to help if you need a hand with this, as well.

**Comment by garfieldnate** [comment]
Quick workaround:

    RUN apt-get update

This ensures that `libmecab-dev` can be downloaded directly instead of needing to be compiled.

That fixes the issue for me, though I still wonder why compiling from source did not work properly.

**Comment by garfieldnate** [comment]
Actually, I think the more important issue is that installing the module didn't fail; it would have been better if this were an install-time failure, rather than a runtime failure.

**Comment by polm** [comment]
I see the error you're getting but I'm also not sure what would cause it. It might be something simple like needing to run ldconfig after compiling the library.

Because shared libs are resolved at runtime in general, there's no reasonable way to make this an install failure instead of a runtime one.

**Comment by garfieldnate** [comment]
Sorry to bother you with this; I think now that I was simply running out of memory during the compilation phase. But I'm still unsure why the build completed successfully without finding mecab. Wouldn't it be beneficial to raise an error at the end of `check_libmecab ` in `fugashi_util.py` instead of returning empty lists?

**Comment by polm** [comment]
> Wouldn't it be beneficial to raise an error at the end of check_libmecab in fugashi_util.py instead of returning empty lists?

I guess, but I'm not sure because that means you couldn't ever run setup.py without a working installation.

**Comment by garfieldnate** [comment]
Sorry to bother you with this if this seems like a silly issue 😅 

>you couldn't ever run setup.py without a working installation.

Exactly. Maybe I want it to be more black-boxy than you intended, but the way I expect `pip install fugashi` to work is that  1) before install I do not have mecab and have no idea how to get mecab, and 2) after install everything works and I don't have to worry about whether mecab is installed. I definitely do not expect 3) fugashi installed successfully but actually the mecab install failed so it doesn't work.

**Comment by lambdadog** [comment]
> Exactly. Maybe I want it to be more black-boxy than you intended, but the way I expect `pip install fugashi` to work is that 1) before install I do not have mecab and have no idea how to get mecab, and 2) after install everything works and I don't have to worry about whether mecab is installed. I definitely do not expect 3) fugashi installed successfully but actually the mecab install failed so it doesn't work.

If `mecab_config_linux_build` functioned correctly then this would never be an issue, so there should be no concern here. If I attempt to install fugashi from source on either MacOS or Windows the *install fails correctly*, it's that there's an additional case for building on Linux if mecab is not found that allows installation to proceed in the first place, then `mecab_config_linux_build` fails to produce a configuration which allows fugashi to work at runtime.

With this install you are experiencing a bug in this branch of the installation procedure. By the nature of fugashi's installation, if this bug in `mecab_config_linux_build` did not exist you would never be able to install fugashi in a way that allowed `libmecab.so.2` to not be found, which is exactly the behavior you're advocating for, this bug in `mecab_config_linux_build` just needs to be isolated and fixed.

**Comment by lambdadog** [comment]
Some notes after digging into this issue:

 - In python 3.9.9, this Dockerfile installs libmecab in `~/.local/lib/mecab` (with ~ being /root)
 - In python 3.10.1, this Dockerfile installs libmecab in `/usr/local/lib/python3.10/site-packages/root/.local/lib/mecab`
   + When pip is run with `--user`, this becomes `~/.local/lib/python3.10/site-packages/root/.local/lib/mecab`
   + When pip is run as non-root with `--user`, this becomes `~./local/lib/python3.10/site-packages/home/$USER/.local/lib/mecab`

So, even if `mecab_config_linux_build()` *isn't* intended to produce a running configuration, its behavior on 3.10 is broken.

**Comment by lambdadog** [comment]
Apologies for the number of edits above, my understanding of the issue kept evolving as I kept digging.

**Comment by lambdadog** [comment]
I'd very much like to see `mecab_config_debian_root()` removed if nothing else, as I'm fairly unhappy with the idea of `pip install fugashi` installing a package using my system package manager, and ideally both `mecab_config_linux_build()` and `mecab_config_debian_user()` can be reworked so their changes are self-contained inside `site-packages` on all supported versions of python and the `extra_link_args` `-rpath` arg can be fixed so the python extension properly links to them.

**Comment by polm** [comment]
For the record, these were all added in #8, so that may be helpful reference. It's true that some of these are rarely used.

What we can do is cut out most of these and leave the responsibility for installing mecab up to the user. As part of that, if no working configuration can be found, we can throw an exception instead of returning empty lists.

My concern with `setup.py` throwing an exception was that maybe there was some informational command, like `setup.py info` or something, that could be useful even without a working setup. But I can't think of anything like that and haven't found one poking around so I guess it's not worth worrying about.

**Comment by polm** [comment]
Test release with these changes is up as 1.1.2a4.

**Comment by garfieldnate** [comment]
If the automation aspect is removed from fugashi, I think it would be a good idea to update the readme with more detailed install instructions (minimum `apt-get update && apt-get install libmecab-dev`). It might be gross to change the user's environment, but it's also pretty convenient for many users XD. There might also be a middle ground where we prompt or use some optional install parameters to determine if mecab should be installed.

**Comment by lambdadog** [comment]
Fugashi will still install automatically for the vast, vast majority of users, to be clear, at least once the Python 3.10 wheels are pushed to PyPI.

That said, probably still not a *terrible idea* to have at least some mention of the install failure state and an example of installing mecab, like Nate mentions.

**Comment by polm** [comment]
Found an issue with the new change - it breaks the sdist upload. Creating an sdist uses setup.py but doesn't require a working MeCab env. So I'll need to hack a workaround for that.

**Comment by polm** [comment]
Hey, I am back working on this again. I should be able to resolve the sdist issues and make a release soon.

One extra issue that came up is getting support for OSX arm64 / M1 processors. I made a test build but I don't have any way of testing it myself; if either of you does, it'd be a big help if you could take a look at #55 and give it a quick test.

**Comment by garfieldnate** [comment]
Sorry, I only have old Mac :(

**Comment by polm** [comment]
Changed the title of this issue to reflect what actually ended up happening. 

The latest release, 1.1.2, incorporates the changes discussed here, so I'll close this, but if I forgot anything let me know.

**Comment by polm** [comment]
Also, for the record, you still can't run `python setup.py sdist` without a working MeCab installation. But since few people need sdist and it's not super useful without MeCab anyway, I just made sure the CI installs it.
