### ISSUE TITLE
Error: Failed initializing MeCab

### ISSUE THREAD

**Issue by balu-r** [polm/fugashi#57]
RuntimeError: 
Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/polm/fugashi

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/polm/fugashi/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments: [b'fugashi', b'-C', b'-r', b'/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/unidic_lite/dicdir/mecabrc', b'-d', b'/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/unidic_lite/dicdir']
viterbi.cpp(50) [tokenizer_->open(param)] tokenizer.cpp(109) [sysdic->open (create_filename(prefix, SYS_DIC_FILE).c_str())] dictionary.cpp(79) [dmmap_->open(file, mode)] no such file or directory: /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-p

**Comment by polm** [comment]
When reporting an error, please explain what you tried and what did not work. Include not only the error message but also your code.

Your error message seems to be cut off, but does the file or directory mentioned there exist?

**Comment by balu-r** [comment]
Sorry for not providing enough info
I am 
Code:

```
import jaconv
import fugashi
from csv import reader


count=0
with open('metadata.csv') as metadata:
    index=-1
    csv_reader = reader(metadata)
    header = next(csv_reader)
    for line in csv_reader:
        tagger = fugashi.Tagger()
        index+=1
        title = line[1]
        title  = jaconv.z2h(title,ascii=True,digit=True)
        words = [word.surface for word in tagger(title)]
        count+=1

print(count)
```

Error:
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-dc05221bd95d> in <module>
     10     header = next(csv_reader)
     11     for line in csv_reader:
---> 12         tagger = fugashi.Tagger()
     13         index+=1
     14         title = line[1]

fugashi/fugashi.pyx in fugashi.fugashi.Tagger.__init__()

fugashi/fugashi.pyx in fugashi.fugashi.GenericTagger.__init__()

RuntimeError: 
Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/polm/fugashi

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/polm/fugashi/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments: [b'fugashi', b'-C', b'-r', b'/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/unidic_lite/dicdir/mecabrc', b'-d', b'/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/unidic_lite/dicdir']
viterbi.cpp(50) [tokenizer_->open(param)] tokenizer.cpp(109) [sysdic->open (create_filename(prefix, SYS_DIC_FILE).c_str())] dictionary.cpp(79) [dmmap_->open(file, mode)] no such file or directory: /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-p
```

error message didn't cut off, it is how the error got displayed.

**Comment by polm** [comment]
OK, thanks for the extra details. I'm not sure but I think you are getting a weird error due to excessive memory use because you are recreating the tagger in the loop (note the `mmap` in your error), similar to #35. Try moving the `tagger = fugashi.Tagger()` to the top of your code and only call it once.

If that doesn't work let me know.

**Comment by balu-r** [comment]
After moving creation of tagger out of loop, it worked.
Thank you @polm

**Comment by polm** [comment]
Glad it worked!
