### ISSUE TITLE
The unidic_lite dictionary is not installed

### ISSUE THREAD

**Issue by rajatbarve** [polm/fugashi#68]
Hi All,

I am using BertJapaneseTokenizer from transformers. However, on calling this tokenizer I see the captioned error. On looking under the hood (https://huggingface.co/transformers/v4.11.3/_modules/transformers/models/bert_japanese/tokenization_bert_japanese.html), it looks like this error can only occur if the variable mecab_dic is set = "unidic_lite"
Due to certain reasons I cannot install _unidic_lite_ (please let's just assume that this is an unavoidable constraint that I have). However, I can and I have installed _unidic_. But I still the  same error. I do not know why it meca_dic defaults to "unidic_lite"

Some might rightly say that simply pip install unidic would not work and I also need explicitly download the dictionary. However, I could have done that if I were working in a Jupyter notebook, but I am not. I am a trying to deploy a model and I am not working in Jupyter workspace. Therefore, while I can do "import fugashi", "import unidic" I cannot use any "install" commands, nor any "download"

(I could be way off about the correct solution so if someone has any other alternative please do share that as well)

Thanks

**Comment by rajatbarve** [comment]
@polm

**Comment by polm** [comment]
I'm not sure I understand your problem entirely, but it sounds like you want to download the UniDic dictionary from code instead of the command line. You can do that like this:

```
from unidic.download import download_version
download_version()
```

The command line `download` command is just a wrapper for that function.

**Comment by rajatbarve** [comment]
> I'm not sure I understand your problem entirely, but it sounds like you want to download the UniDic dictionary from code instead of the command line. You can do that like this:
> 
> ```
> from unidic.download import download_version
> download_version()
> ```
> 
> The command line `download` command is just a wrapper for that function.

Thank you @polm!

But I am still getting the error "The unidic_lite dictionary is not installed". 
My model is making a call to the class BertJapaneseTokenizer. (I would request you to take a look at the source code here. It will greatly facilitate my explanation: [https://huggingface.co/transformers/v4.11.3/_modules/transformers/models/bert_japanese/tokenization_bert_japanese.html]

You will see that on following the trail of function calls in reverse, it looks like that error can occur only when the variable _mecab_dic_ is equal to = 'unidic_lite' (mecab_dic is an attribute of the class MecabTokenizer that you will also find in the link above).

My question is can I override this value of mecab_dic and change it to "unidic" instead of the current "unidic_lite"

That way I will not get the error.

**Comment by polm** [comment]
Closing for lack of response / because this issue isn't relevant to fugashi directly. 

For the record, if you want help with this you should show the code where you're using BertJapaneseTokenizer and explain what you're actually trying to do. It sounds like you have a usage question about the HuggingFace code, but with just the information you've given there's no way to tell what's going on.
