### ISSUE TITLE
Offer bundled MeCab

### ISSUE THREAD

**Issue by polm** [polm/fugashi#7]
Some users have difficulty installing and configuring MeCab, so it would be good to provide wheels with it bundled. The way [mecab-python3 did this](https://github.com/polm/mecab-python3/blob/master/scripts/build-bundled-libmecab.py) may be a useful reference.

On the other hand, this shouldn't be done by default since it requires including a dictionary, which makes the install very large.

**Comment by KoichiYasuoka** [comment]
Just made a PR #8 "Automatic bundling libmecab" without dictionaries. How about it?

**Comment by polm** [comment]
So I merged your PR but now the Windows wheel build is breaking, it seems to be unable to find `mecab.h`... I'll try to figure out what's up.

**Comment by KoichiYasuoka** [comment]
Oops, I've found `win_bin_dir`, which seems unassigned, in [fugashi_util.py](https://github.com/polm/fugashi/blob/4050974debcf14fe07a150b6e7cd70191d7d2664/fugashi_util.py#L18)...

**Comment by polm** [comment]
OK, I have fixed the Windows wheel builds, and there's a working Linux build, so I'll close this for now.
