### ISSUE TITLE
Installing error when using `python:alpine` as the base image

### ISSUE THREAD

**Issue by rabbit19981023** [polm/fugashi#77]
Hello,

I'm trying to bundle my app into a docker image.

When using `python:alpine` as the base image, it causes errors like this (while `python:slim` doesn't cause this error):

```
#0 22.01   Downloading fugashi-1.2.1.tar.gz (337 kB)
#0 22.08      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 338.0/338.0 kB 4.7 MB/s eta 0:00:00
#0 22.11   Preparing metadata (setup.py): started
#0 22.86   Preparing metadata (setup.py): finished with status 'error'
#0 22.87   error: subprocess-exited-with-error
#0 22.87
#0 22.87   × python setup.py egg_info did not run successfully.
#0 22.87   │ exit code: 1
#0 22.87   ╰─> [9 lines of output]
#0 22.87       Traceback (most recent call last):
#0 22.87         File "<string>", line 2, in <module>
#0 22.87         File "<pip-setuptools-caller>", line 34, in <module>
#0 22.87         File "/tmp/pip-install-wxx7nb2x/fugashi_e3388a1cdbb74184951bb5024087448f/setup.py", line 15, in <module>
#0 22.87           output, data_files = check_libmecab()
#0 22.87                                ^^^^^^^^^^^^^^^^
#0 22.87         File "/tmp/pip-install-wxx7nb2x/fugashi_e3388a1cdbb74184951bb5024087448f/fugashi_util.py", line 58, in check_libmecab
#0 22.87           raise RuntimeError("Could not configure working env. Have you installed MeCab?")
#0 22.87       RuntimeError: Could not configure working env. Have you installed MeCab?
#0 22.87       [end of output]
#0 22.87
#0 22.87   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 22.87 error: metadata-generation-failed
#0 22.87
#0 22.87 × Encountered error while generating package metadata.
#0 22.87 ╰─> See above for output.
#0 22.87
#0 22.87 note: This is an issue with the package mentioned above, not pip.
#0 22.87 hint: See above for details.
```

I'm not sure if it's just that mecab doesn't support the platform, or there's something missing in `check_libmecab()`.

**Comment by polm** [comment]
This happens if you build from source and don't have MeCab installed previously. fugashi will not install MeCab for you. 

It seems likely you're using something that doesn't have a wheel - what version of Python and what architecture are you using?

**Comment by rabbit19981023** [comment]
This is the Dockerfile that causes this problem:

```dockerfile
FROM python:alpine

RUN pip install fugashi
```

And run `docker inspect python:alpine` to check the architecture:

```
[
    {
        ......
        "Env": [
                ......
                "PYTHON_VERSION=3.11.4",
                "PYTHON_PIP_VERSION=23.1.2",
                "PYTHON_SETUPTOOLS_VERSION=65.5.1",
                ......
            ],
        "Architecture": "amd64",
        "Os": "linux",
        ......
    }
]
```

**Comment by polm** [comment]
Hm, those images both seem to have the same architecture, so not sure what's up. Can you check the verbose output of pip for both of them and see why it decides to install from source instead of from a wheel?

**Comment by rabbit19981023** [comment]
Finally I found the reason why this happens: Alpine Linux uses musl, while manylinux wheels are based on glibc. (See pypa/pip#9735)

And I also found the working tags for Alpine are `*-py3-none-any.whl` or `*-cp311-cp311-musllinux_1_1_x86_64.whl`.

**Comment by polm** [comment]
Thank you for clarifying, that is something that wouldn't have occurred to me.

Since nobody has ever brought this up before, I don't consider it a priority at the moment, though I understand Alpine is widely used. If someone would like to make a PR to add musl packages to wheel builds I'd be happy to consider it.

In the meantime, you can install MeCab before fugashi, and then building fugashi from source should be fast and work without issue.

**Comment by rabbit19981023** [comment]
I would just use `python:slim`, it's more straightforward and also suites my needs (have a small-size container).

And maybe just need to mention this issue in README would help most of the users.

**Comment by polm** [comment]
Thank you for the clarification. I updated the README with a list of platforms for which wheels are not available.
