### ISSUE TITLE
Failed initializing MeCab

### ISSUE THREAD

**Issue by eye-zhuk** [polm/fugashi#78]
RuntimeError:
Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/polm/fugashi

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/polm/fugashi/issues

issueを英語で書く必要はありません。
what should i do here?

**Comment by polm** [comment]
So the error message you have copied and pasted mentions ERROR DETAILS. Did your output not include ERROR DETAILS? It should look a little like this:

```
------------------- ERROR DETAILS ------------------------
arguments: [b'fugashi', b'-C', b'-d', b'/aasdf']
param.cpp(69) [ifs] no such file or directory: /aasdf/dicrc
----------------------------------------------------------
```

Please also check the [common issues](https://github.com/samurait/mecab-python3#common-issues). For example, did you install a dictionary like `unidic-lite`?

**Comment by eye-zhuk** [comment]
yes the error code looks like this
arguments: [b'fugashi', b'-C', b'-d', b'C:\\Users\\Me\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\unidic_lite\\dicdir', b'-r', b'C:\\Users\\Me\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\unidic_lite\\dicdir\\mecabrc']
viterbi.cpp(50) [tokenizer_->open(param)] tokenizer.cpp(110) [sysdic->open (create_filename(prefix, SYS_DIC_FILE).c_str())] dictionary.cpp(94) [(magic ^ DictionaryMagicID) == dmmap_->size()] dictionary file is broken: C:\Users\Me\AppData\Local\Programs\

**Comment by polm** [comment]
Please read the [markdown formatting guide](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code). 

The error says your dictionary is broken. Can you try reinstalling unidic lite?

Also please provide a sample of the code that causes this. mmap related errors are often related to creating too many instances of the Tagger.

**Comment by polm** [comment]
Closing due to lack of response.
