### ISSUE TITLE
huggingface tokenizer APIへの準拠

### ISSUE THREAD

**Issue by nassie256** [polm/fugashi#90]
hotchpotch/japanese-reranker-cross-encoder-large-v1 という日本語Rerankerモデルがfugashi[unidic-lite]に依存していて、そのモデルを、SentenceTransformersをREST APIとしてサーブするInfinity というOSSから利用しようとしたところ、動作しませんでした。
Infinity でissueを立てて確認したところ、fugashiが huggingface tokenizer API に完全準拠していないことが原因と判明しました。
https://github.com/michaelfeil/infinity/issues/192

fugashi をhuggingface tokenizer APIへ準拠させることは可能でしょうか？ それは現実的でしょうか？

**Comment by polm** [comment]
Transformers で fugashi を使う場合、直接 fugashi の Tagger object を Tokenizer として使うのではなく、 wrapper を通して使う必要があります。既存のものとして BertJapaneseTokenizer が参考になると思います。

https://github.com/huggingface/transformers/blob/b17b54d3dd3093815d375c2a78d5b3a0661c3c8d/src/transformers/models/bert_japanese/tokenization_bert_japanese.py#L409

**Comment by polm** [comment]
こちらで実装するものではないので、この issue を close します。
