### ISSUE TITLE
Failed initializing MeCab

### ISSUE THREAD

**Issue by Sueteur** [polm/fugashi#93]
Hi I am facing the issue below:

出错了： Failed initializing MeCab. Please see the README for possible solutions: https://github.com/polm/fugashi If you are still having trouble, please file an issue here, and include the ERROR DETAILS below: https://github.com/polm/fugashi/issues issueを英語で書く必要はありません。 ------------------- ERROR DETAILS ------------------------ arguments: [b'fugashi', b'-C'] param.cpp(69) [ifs] no such file or directory: c:\mecab\mecabrc ----------------------------------------------------------

I am using your cloning voice.
My case is that, I uploaded a Japan voice and typing some Japanese sentences to see if it works. However, this error popped up. No problem when using English and Chinese. This error only occur when I used Japanese.

Could you please help me on this issue?
Thanks in advance!

**Comment by tinhtn22** [comment]
I used cutlet to convert Japanese to romaji, but I got an error about initialize MeCab from fugashi

**Code:**
```python
import cutlet
conv = cutlet.Cutlet()
```

**Error detail:**
```
  File "C:\user\ap\env\lib\site-packages\cutlet\cutlet.py", line 82, in __init__
    self.tagger = fugashi.Tagger()
  File "fugashi\fugashi.pyx", line 345, in fugashi.fugashi.Tagger.__init__
  File "fugashi\fugashi.pyx", line 231, in fugashi.fugashi.GenericTagger.__init__
RuntimeError: 
Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/polm/fugashi

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/polm/fugashi/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments: [b'fugashi', b'-C', b'-r', b'C:\\user\\ap\\env\\lib\\site-packages\\unidic_lite\\dicdir\\mecabrc', b'-d', b'C:\\user\\ap\\env\\lib\\site-packages\\unidic_lite\\dicdir']
viterbi.cpp(50) [tokenizer_->open(param)] tokenizer.cpp(110) [sysdic->open (create_filename(prefix, SYS_DIC_FILE).c_str())] dictionary.cpp(79) [dmmap_->open(file, mode)] no such file or directory: C:\user\ap\env\lib\site-packages\unidic_lite\dicdir\sy
----------------------------------------------------------
```

It seem like the fugashi could not references to sys.dic file from `unidic_lite/dicdir` folder, with a abnormal file name (`\sy` instead of `\sys.dic`.
Could you suggest any solution to solving the issue?

**Environment:**
cutlet==0.1.19
fugashi==1.1.2
mecab-python3==1.0.5
unidic-lite==1.0.8

Thank you very much.

P/S: Please tell me if it just logging error for the path.
