### ISSUE TITLE
Interactive demo is broken

### ISSUE THREAD

**Issue by joshdavham** [polm/fugashi#94]
The [streamlit app](https://polm-fugashi-streamlit-demo-demo-blqthk.streamlit.app/) linked to in the README is currently broken. 

Also, where could I find the code for that streamlit app?

**Comment by polm** [comment]
Thanks for the heads up! I think I have to just update dependencies.

There's really not much to it, but the source is here: https://github.com/polm/fugashi-streamlit-demo

**Comment by polm** [comment]
This should be resolved now, thanks for updating the dependencies in the demo.

Note the URL has changed, as I had to delete and recreate the app, and the previous URL violates current Streamlit URL policies.
